### ISSUE TITLE
Criar protótipo de tela de Cadastro de Medicações no Figma (Front-end)

### ISSUE THREAD

**Issue by raffaelfernandes** [ES2-UFPI/Remedius#33]
- Prototipação de tela para Cadastro de Medicações no Figma para a aplicação Remedius, permitindo inserir e salvar todas as informações básicas, de horários e frequência e detalhes adicionais de medicações.

**Comment by raffaelfernandes** [comment]
![Cadastro de Medicações_ProtótipoTela](https://github.com/user-attachments/assets/0c32cf34-5844-47c2-8d25-2acde4a7d678)

**Comment by LuisEnilton** [comment]
Tela Correta.
