### ISSUE TITLE
Criação do protótipo de tela para Monitoramento de Estoque (Front-end)

### ISSUE THREAD

**Issue by emerymoriconi** [ES2-UFPI/Remedius#54]
Tarefa inicial de design de interface com uso de ferramentas de prototipação.

**Comment by raffaelfernandes** [comment]
![EstoqueDeMedicacoes_PrototipoTela](https://github.com/user-attachments/assets/3f436b2c-fe9f-4a1a-9e19-df1a0032ee5d)
